name: desafio_supremo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  equatable: ^2.0.3
  either_dart: ^0.1.4
  intl: ^0.17.0
  bloc: ^8.0.3
  bloc_test: ^9.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  timelines: ^0.1.0
  shimmer: ^2.0.0
  screenshot: ^1.2.3
  share_plus: ^4.0.10
  path_provider: ^2.0.11
  lottie: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.2.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/progress.json
    - assets/images/error_image.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
