name: desafio_supremo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository

  form_inputs:
    path: packages/form_inputs

  bloc:
  flutter_bloc:  
  get_it: ^7.2.0
  equatable: ^2.0.3
  flow_builder: ^0.0.9  
  formz: ^0.4.0
  google_fonts: ^3.0.1
  meta: ^1.7.0
  http: ^0.13.4
  either_dart: ^0.1.4
  intl: ^0.17.0    
  shimmer: ^2.0.0
  flutter_svg: ^1.1.3
  percent_indicator: ^4.2.2
  screenshot: ^1.2.3
  share_plus: ^4.0.10
  path_provider: ^2.0.11
  lottie: ^1.4.0
  onboarding: ^3.1.0
  introduction_screen: ^3.0.2
  confetti: ^0.7.0
  firebase_core:
  firebase_auth: ^3.6.3
  connectivity_plus: ^2.3.6+1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.0.0
  flutter_lints: ^2.0.0
  mockito: ^5.2.0
  build_runner: ^2.2.0
  lints: ^2.0.0
  bloc_test: ^9.0.3
  dependency_validator: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/NoBank3.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
