name: desafio_supremo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  equatable: ^2.0.3
  either_dart: ^0.1.4
  intl: ^0.17.0
  bloc: ^8.0.3
  bloc_test: ^9.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  timelines: ^0.1.0
  shimmer: ^2.0.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.3
  percent_indicator: ^4.2.2
  screenshot: ^1.2.3
  share_plus: ^4.0.10
  path_provider: ^2.0.11
  lottie: ^1.4.0
  onboarding: ^3.1.0
  introduction_screen: ^3.0.2
  carousel_slider: ^4.1.1
  awesome_card: ^1.1.7
  bloc_concurrency: ^0.2.0
  zwidget: ^0.0.2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
  simple_animations: ^4.2.0
  animate_do: ^2.1.0
  supercharged: ^2.1.1
  fl_chart: ^0.55.1
  smooth_page_indicator: ^1.0.0+2
  mask_text_input_formatter: ^2.4.0
  hive: ^2.2.3
  hydrated_bloc: ^8.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.2.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
