// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp3CEqSIMby6Xxn07J1Yur_1wxdw6zJOg',
    appId: '1:1021179714288:web:fa295ed1e397a1782c0035',
    messagingSenderId: '1021179714288',
    projectId: 'nobank',
    authDomain: 'nobank.firebaseapp.com',
    storageBucket: 'nobank.appspot.com',
    measurementId: 'G-X4WD9DXZLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXxRlyqRAqav18hL5OseLkxM0LrGOnrAE',
    appId: '1:1021179714288:android:8fa23031e13f85102c0035',
    messagingSenderId: '1021179714288',
    projectId: 'nobank',
    storageBucket: 'nobank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ORqZxIXHy2_AmWt-Hzh3qKDFjTIFAxg',
    appId: '1:1021179714288:ios:2a395df360e2a7cb2c0035',
    messagingSenderId: '1021179714288',
    projectId: 'nobank',
    storageBucket: 'nobank.appspot.com',
    iosClientId: '1021179714288-ik8o9nhqevcf35ugl35922ivpjd3tj14.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioSupremo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ORqZxIXHy2_AmWt-Hzh3qKDFjTIFAxg',
    appId: '1:1021179714288:ios:2a395df360e2a7cb2c0035',
    messagingSenderId: '1021179714288',
    projectId: 'nobank',
    storageBucket: 'nobank.appspot.com',
    iosClientId: '1021179714288-ik8o9nhqevcf35ugl35922ivpjd3tj14.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioSupremo',
  );
}
